/*@StepGroupList
{
  "groups": [
    "lambda_reg_navigation.sg",
    "test.sg"
  ]
}
*/

// ************************** IMPORTANT **************************
// This file is auto-generated by PlayQ for Step Group.
// Do not edit it manually. File is auto-generated.
// Any changes done directly will be lost on the next generation.
// ***************************************************************

import { Given } from '@cucumber/cucumber';

Given('Step Group: -lambda_reg_navigation.sg- -Navigating to Lambda Test Registration Page-', async function () {
    /*StepGroup:lambda_reg_navigation.sg
        * Web: I open web browser with "${env.lambdatest.url}"
        * Web: I open web browser with "${env.lambdatest.url}"
        * Web: Verify page title is "Your store" options: "partial_check: true, case_sensitive: false"
        * Web: Mouseover on link "{{top_menu}} My account" options: ""
        * Web: Click link "Register" options: ""
        * Web: Verify header text is "Register Account" options: ""
        * Web: Wait in milliseconds "200"
    */
});

Given('Step Group: -test.sg- -testing Step Group-', async function () {
    /*StepGroup:test.sg
        * Web: Verify header text is "Register Account" options: ""
    */
});
